### ISSUE TITLE
Problems with running dev server

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/docs#197]
```
Jacek@AsusNotebook ~/vuetifyjs/docs
$ git fetch upstream

Jacek@AsusNotebook ~/vuetifyjs/docs
$ git merge upstream/dev
Already up-to-date.

Jacek@AsusNotebook ~/vuetifyjs/docs
$ npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN vuetify-docs@0.0.5 No repository field.
npm WARN vuetify-docs@0.0.5 No license field.

Jacek@AsusNotebook ~/vuetifyjs/docs
$ git branch
* dev
  fix/duplicated-badge-arg-left
  fix/footer-props
  fix/navigation-drawers
  fix/tooltip-default-visible-value
  grid-align-content-props

Jacek@AsusNotebook ~/vuetifyjs/docs
$ npm run dev

> vuetify-docs@0.0.5 dev C:\cygwin64\home\Jacek\vuetifyjs\docs
> node server

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:8080
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1258:14)
    at listen (net.js:1294:10)
    at net.js:1404:9
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
```

**Comment by nekosaur** [comment]
Still having issues with this @jacekkarczmarczyk? Looks like you were just hosting something else on port `8080` at the same time.
